#ifndef UNSPREGS_H
#define UNSPREGS_H

#define REGISTER(addr) *(unsigned int*)addr

// GPIO //
#define GPIO_CONFIG REGISTER(0x3d00)

#define PORTA_DATA   REGISTER(0x3d01)
#define PORTA_BUFFER REGISTER(0x3d02)
#define PORTA_DIR    REGISTER(0x3d03)
#define PORTA_ATTR   REGISTER(0x3d04)
#define PORTA_MASK   REGISTER(0x3d05)

#define PORTB_DATA   REGISTER(0x3d06)
#define PORTB_BUFFER REGISTER(0x3d07)
#define PORTB_DIR    REGISTER(0x3d08)
#define PORTB_ATTR   REGISTER(0x3d09)
#define PORTB_MASK   REGISTER(0x3d0a)

#define PORTC_DATA   REGISTER(0x3d0b)
#define PORTC_BUFFER REGISTER(0x3d0c)
#define PORTC_DIR    REGISTER(0x3d0d)
#define PORTC_ATTR   REGISTER(0x3d0e)
#define PORTC_MASK   REGISTER(0x3d0f)

// TIMERS //
#define TIMEBASE_CTRL  REGISTER(0x3d10)
#define TIMEBASE_CLEAR REGISTER(0x3d11)

#define TIMERA_ENABLE REGISTER(0x3d14)
#define TIMERA_IRQACK REGISTER(0x3d15)

#define TIMERB_ENABLE REGISTER(0x3d18)
#define TIMERB_IRQACK REGISTER(0x3d19)

// SYSTEM //
#define SYSTEM_CTRL REGISTER(0x3d20)
#define IRQ_CTRL    REGISTER(0x3d21)
#define IRQ_ACK     REGISTER(0x3d22)
#define MEMORY_CTRL REGISTER(0x3d23)
#define WATCHDOG    REGISTER(0x3d24)

// ADC //
#define ADC_CTRL REGISTER(0x3d25)
#define ADC_DATA REGISTER(0x3d27)

// SLEEP //
#define SLEEP_CTRL   REGISTER(0x3d28)
#define WAKEUP_SRC   REGISTER(0x3d29)
#define WAKEUP_DELAY REGISTER(0x3d2a)

// PAL / NTSC //
#define PAL_NTSC REGISTER(0x3d2b)

// PRNG //
#define PRNG1 REGISTER(0x3d2c)
#define PRNG2 REGISTER(0x3d2d)

// FIQ //
#define FIQ_SEL REGISTER(0x3d2e)

// DS //
#define DATA_SEGMENT REGISTER(0x3d2f)

// UART //
#define UART_CTRL   REGISTER(0x3d30)
#define UART_STAT   REGISTER(0x3d31)
#define UART_RESET  REGISTER(0x3d32)
#define UART_BAUDLO REGISTER(0x3d33)
#define UART_BAUDHI REGISTER(0x3d34)
#define UART_TX     REGISTER(0x3d35)
#define UART_RX     REGISTER(0x3d36)

// SPI //
#define SPI_CTRL REGISTER(0x3d40)
#define SPI_DATA REGISTER(0x3d41)
#define SPI_CLK  REGISTER(0x3d42)

// I2C //
#define IIC_CMD     REGISTER(0x3d58)
#define IIC_STAT    REGISTER(0x3d59)
#define IIC_ACCESS  REGISTER(0x3d5a)
#define IIC_DEVADDR REGISTER(0x3d5b)
#define IIC_SUBADDR REGISTER(0x3d5c)
#define IIC_DATAOUT REGISTER(0x3d5d)
#define IIC_DATAIN  REGISTER(0x3d5e)
#define IIC_CTRLR   REGISTER(0x3d5f)

// DMA Controller //
#define DMA_SRCLO REGISTER(0x3e00)
#define DMA_SRCHI REGISTER(0x3e01)
#define DMA_SIZE  REGISTER(0x3e02)
#define DMA_DST   REGISTER(0x3d03)


#endif // UNSPREGS_H
